version: '3.3'

services:

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app
    ports:
      - 27018:27018
    volumes:
      - :/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    # depends_on:
    #   - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks: 
      - app

networks:
  app:
    driver: bridge 

# 1. Run and test/make migrate with a running container:     
# docker exec -it <container_id with docker ps> sh

# 2. Volume: (Real folder):(Virtual folder) --> Purpose: Backup data

# 3. Build container from Dockerfile instead of pure image(s): 
# build:
#   context: ./backend
#   dockerfile: Dockerfile

# 4.  